### ISSUE TITLE
메모리 문제 해결

### ISSUE THREAD

**Issue by smallfish06** [CAU-OSS-2019/team-project-team06#11]
만약에 넣는 PDF 양이 많고 담은 텍스트의 크기가 크다면 키워드 추출 도중 문제가 생기거나 메모리가 부족할 수 있다고 생각합니다. 그럴 경우를 대비하여 데이터를 일정 개수만큼씩만 읽고 처리하여 반복하는 방식으로 구현해도 좋을 것 같습니다.

**Comment by minjoong507** [comment]
이슈 감사합니다. 아직 많은 데이터를 돌려보진 못했지만 충분히 생길 수 있는 문제라고 생각합니다.  이슈에 남겨주신대로 코드가 구현된다면 pull request를 보내주시면 감사하겠습니다.
