### ISSUE TITLE
file을 upload할때 하나씩 업로드해야 하는 단점이 있습니다.

### ISSUE THREAD

**Issue by ccwhan6** [CAU-OSS-2019/team-project-team06#13]
file을 upload할때 하나씩 업로드해야 하고 그때마다 새로 고침되는 단점이 있습니다.
키워드를 찾기 위해 여러 파일을 넣어야 되는데 그 때마다 파일을 하나씩 선택해야하는 귀찮은 문제가 있습니다.
이때 여러파일을 한 번에 업로드하면 사용자에게 훨씬 더 유용한 기능이 될 것 같습니다.

**Comment by janghyukjin** [comment]
우선 이슈 감사드립니다!
file upload시에 multiple files로 업로드하면 더욱 편할 것 같다고 평소에 생각하고 있었습니다.
코드 수정하여 pull-request날리시면 merge해드리겠습니다!
감사합니다:)

**Comment by TheSuPIsTar** [comment]
#17
