### ISSUE TITLE
주석 처리 필

### ISSUE THREAD

**Issue by TheSuPIsTar** [CAU-OSS-2019/team-project-team06#14]
처음 이 프로젝트에 참가한 사람이 코드를 알아보기 위한 주석 처리가 필요할 것 같습니다. 저는 mainapp의 view 등의 파일을 봤는데 주석이 없어 내용을 파악하기 어려웠습니다. 전체적인 주석 처리 희망합니다.

**Comment by minjoong507** [comment]
Issue 감사드립니다. 저희 팀원들끼리 상의하여 코드이해가 쉽도록 주석처리하여 올리도록 하겠습니다. 감사합니다!
