### ISSUE TITLE
하이라이팅 색상 사용자설정

### ISSUE THREAD

**Issue by simba328** [CAU-OSS-2019/team-project-team06#16]
현재 pull request (#4)에서 하이라이팅하는 색상을 변경하려면 코드를 수정해야 한다는 점을 발견했습니다. 사용자 편의성을 위해 유저가 직접 색상 설정을 할 수 있는 기능을 추가하고자 하는데 괜찮을까요?

**Comment by shawn159** [comment]
팀 내부에서도 해당부분 기능을 추가하는 것에 대해서 의견이 있었습니다. 사용자로부터 색상을 입력받아 결과물에 해당 색을 반영하는 부분까지 모두 구현해 주신다면, 테스트 후 머지하도록 하겠습니다.
