### ISSUE TITLE
index.html에 upload함수가 ajax 통신에 문제가 있는 것 같습니다.

### ISSUE THREAD

**Issue by cloudhs7** [CAU-OSS-2019/team-project-team06#19]
index.html에 upload함수가 ajax 통신에 문제가 있는 것 같습니다.
upload함수가 ajax 통신이 아닌 그냥 form data로 넘어가
업로드할 때마다 비동기적 처리가 아니라 계속 새로고침이 되는 것 같습니다!
확인 부탁드립니다:)

**Comment by janghyukjin** [comment]
이슈 감사합니다!!
확인해보니 ajax전에 form data로 넘어가서 새로고침이 안되었던 것 같습니다.
수정하겠습니다!
감사합니다:)
