### ISSUE TITLE
웹 서비스시 불필요한 sub path가 있습니다.

### ISSUE THREAD

**Issue by simba328** [CAU-OSS-2019/team-project-team06#20]
현재 웹페이지를 접속할 때 localhost/mainapp 이라는 불필요한 subpath가 있습니다. 그렇기 때문에 localhost로 바로 접속할 수 있게 하는 것이 좋을 것 같습니다.

**Comment by ajs7270** [comment]
넵 확인하였습니다. 수정하시고 pull request를 보내주신다면 merge해 드리겠습니다. 감사합니다.
