### ISSUE TITLE
highlight.py 코드 중 의미를 알 수 없는 2차원 배열이 있습니다.

### ISSUE THREAD

**Issue by cloudhs7** [CAU-OSS-2019/team-project-team06#22]
헤당 코드를 읽어보니 코드의 알고리즘이 하이라이팅 해야하는 단어의 좌표를 리스트에 저장한 후 해당 단어들을 한번에 진행하는 것으로 보입니다.
이러한 단어들을 word_location_list에 저장하는 것으로 보이는데 왜  굳이 왜 2차원 배열로 해당 좌표를 참조하는지 의문이 들어 이슈를 남깁니다. 혹시 다른 의미가 있는 것인가요??

**Comment by shawn159** [comment]
아 해당 코드에 관해 리퀘스트가 활발히 진행되어 컨트리뷰터 분들이 더욱 편리하게 컨트리뷰트를 할 수 있도록 해당 코드를 리팩토링 하였습니다. 이를 진행하면서 단어들의 좌표를 저장하는 부분이 필요했고, 리스트를 이용하여 구현하였는데 해당 좌표를 저장하면서 리스트 앞에 '0' 이 추가되는 상황이 벌어졌습니다.
하지만 저도 원인을 알 수 없어 2차원 배열로 진행하였습니다. 혹시 원인을 분석하여 고쳐서 풀리퀘스트 보내주시면 머지하도록 하겠습니다 감사합니다.
