### ISSUE TITLE
웹에서는 정상 작동하는데 local에서 python file이 실행이 안됩니다.

### ISSUE THREAD

**Issue by sangminBangbada** [CAU-OSS-2019/team-project-team06#23]
웹에서는 정상 작동되는 것을 확인했습니다. 근데 터미널을 통해 pdf2jpg.py를 실행했을 때에는 여러 오류 메시지가 뜨며 실행이 안되는 것을 확인했습니다.
관련 오류들을 고쳐 웹과 local 단에서 모두 실행 될 수 있게 하여 pull request 하도록 하겠습니다.

**Comment by donghoney** [comment]
확인하였습니다. pull request 보내주시면 test 후 merge 하도록 하겠습니다.
감사합니다!
