### ISSUE TITLE
하이라이팅 색깔을 결정하는 방식에 문제가 있습니다.

### ISSUE THREAD

**Issue by njw1204** [CAU-OSS-2019/team-project-team06#3]
현재는 하이라이팅할 영역의 색깔을 (R, G, B)에서 (255 - R, 255 - G, 255 - B)로 바꾸는 방식으로 하이라이팅을 하고 있는데, 이 방식에는 문제가 있습니다.
만약 원래 색깔이 (127, 127, 127)이라면 하이라이팅 후 색깔은 (128, 128, 128)으로 육안으로 차이를 확인할 수 없을 것입니다. 또한 하이라이팅 색깔이 각각의 영역마다 달라서 고르지 않다는 문제도 있습니다.
RGB값이 127에 가까우면 하이라이팅 효과가 거의 나타나지 않으므로, 하이라이팅 색깔을 결정하는 방식을 바꿔야한다고 생각합니다.

**Comment by ajs7270** [comment]
이슈 감사합니다. 본 이슈에 대해서는 발표에서도 언급했듯이 인지하고 있었고, 수정할 내용이였습니다. 
본 이슈에 대해서 다양한 색상값으로 하이라이팅을 구현하여 Pull requests를 보내주신다면  Merge해 드리겠습니다.

**Comment by njw1204** [comment]
답변 감사합니다. 작업 후 pull request를 보내겠습니다.

**Comment by njw1204** [comment]
#4
