### ISSUE TITLE
README에 오타가 있습니다

### ISSUE THREAD

**Issue by friedcoke** [CAU-OSS-2019/team-project-team06#5]
installation에 To install package에서 3번째 줄에
pip install -r requirements.txt 이라 명시 되어 있는데
파일은 requirement.txt 이네요 일치 시켜야 혼동이 없을 듯 합니다.

**Comment by friedcoke** [comment]
또 명령 실행 시 resource 패키지 설치에서 에러가 발생합니다
![error](https://user-images.githubusercontent.com/12199155/58528518-c274cc00-8211-11e9-9b96-fa083d4f293a.png)

**Comment by donghoney** [comment]
오타 수정 완료했습니다.

**Comment by donghoney** [comment]
발생한 에러에 대해서는 requirement.txt의 pkg-resources==0.0.0를 제거해주어서 해결했습니다. 감사합니다.
