### ISSUE TITLE
설치 가이드에 nltk 모듈 설치 방법이 추가되어야 합니다.

### ISSUE THREAD

**Issue by njw1204** [CAU-OSS-2019/team-project-team06#6]
Python 3.6 환경에서 README.md의 내용대로 설치했으나, nltk의 averaged_perceptron_tagger 모듈이 없다며 실행되지 않았습니다. 검색을 통해 해결하긴 했으나 이에 대한 내용이 README.md에 추가될 필요성이 있는 것 같습니다.

**Comment by minjoong507** [comment]
코드에 nltk.download() 부분을 추가하여 수정하였습니다. 아직 커밋을 하지 않은 상태라 추가해놓겠습니다.
