### ISSUE TITLE
실행시 PDFInfoNotInstalled Error 가 뜹니다.

### ISSUE THREAD

**Issue by jjiijj78** [CAU-OSS-2019/team-project-team06#7]
Python 3.7.2 환경에서 실행시켰을시에, PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in the PATH 에러가 발생합니다.
확인부탁드립니다.감사합니다.

**Comment by janghyukjin** [comment]
확인해보니 pdf2image package인 poppler가 설치되어 있지 않아 생겼던 오류 같습니다. 해당 설치방법은 https://github.com/Belval/pdf2image 을 참조해주시면 감사하겠습니다.
또한 해당 내용 README.md에 추가시켜 놓겠습니다! 감사합니다:)

**Comment by jjiijj78** [comment]
해결 했습니다. 감사합니다
