### ISSUE TITLE
Django가 Single thread로 동작하기 때문에 발생하는 불편함이 있습니다.

### ISSUE THREAD

**Issue by hyunjae-lee** [CAU-OSS-2019/team-project-team06#8]
현재 서비스가 Single thread로 동작하기 때문에 처리가 끝날 때까지 웹페이지를 전환하지 못하고 기다려야하는 문제가 있습니다.

만약 하이라이트를 추출하는 중간에 페이지를 전환하면 작업이 정지되기 때문에 사용자는 불편함을 겪을 수 있다고 생각합니다. 이를 Multi thread로 동작하게 한다면 조금 더 좋은 프로그램이 될 것 같습니다.

**Comment by ajs7270** [comment]
이슈 감사합니다. 
본 이슈에 관해서는 인지하고 있었지만 수정하지 않은 상태였습니다. 

본 이슈에 대해서 구현 뒤 Pull request 요청을 보내주신 다면 merge해 드리겠습니다.
감사합니다.

**Comment by hyunjae-lee** [comment]
답변 감사합니다.
